### ISSUE TITLE
Fix sound class errors

### ISSUE THREAD

**Issue by FredericBlum** [pano-tacanan-history/oliveiraprotopanoan#46]
@MuffinLinwist Once you are done with BPT, I'd ask you to also fix the tildes in this dataset. Please proceed identically as with the other dataset, replacing the tilde through the cognate-set editor and fixing the alignments immediately for all cognate sets.

Once this is done, there are some 8 or 9 sound class errors which I'd ask you to take a look at and fix if possible. If it is not obvious what is to be done, leave them as is and I will check them.

**Comment by Tarotis** [comment]
I have fixed all sound class errors except the tildes

**Comment by Tarotis** [comment]
Important: Please go through the list by the arrow keys, and not via "Enter". This way, the alignments will not have to be re-done.
